### ISSUE TITLE
Running any command throws an error the DB

### ISSUE THREAD

**Issue by marciogranzotto** [bondhome/bond-cli#3]
Running any command throws an error on `database.py`.

```bash
$ python -m bond discover                                                                                                              [15:15:22]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/marciorodrigues/Documents/Olibra/code/bond-cli/bond/__main__.py", line 6, in <module>
    app.run()
  File "bond/app.py", line 18, in run
    bond.database.load()
  File "bond/database/database.py", line 18, in load
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by marciogranzotto** [comment]
Ohh. That's because it has to be ran with `python3`!

**Comment by BradTotaro** [comment]
#6 mitigates the copy paste devils.
